# Generated by Django 5.1.4 on 2025-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting_bid_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="start_price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
