# Generated by Django 5.1.5 on 2025-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_bid_winner_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elettronica", "Elettronica"),
                    ("gaming", "Gaming"),
                    ("elettrodomestici", "Elettrodomestici"),
                    ("casa", "Casa e Giardino"),
                    ("diy", "Fai da te"),
                    ("collezionismo", "Collezionismo"),
                    ("moda", "Moda"),
                    ("sport", "Sport"),
                    ("motori", "Motori"),
                    ("altro", "Altro"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
